server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    sentinel:
      filter:
        enabled: fasle
    gateway:
      enabled: true
      discovery:
        locator:              #与eureka服务发现结合，通过ServiceId转发到对应服务
          lower-case-service-id: true
#          enabled: true      #开启则sentinel限流不会生效
      routes:
        - id: user_route       #路由的ID，没有固定规则但要求唯一，简易配合服务名；sentinel通过ID限流对应的服务
          uri: lb://user       #匹配后提供服务的路由地址
          predicates:
            - Path=/user/**    #断言，路径相匹配的进行路由


eureka:
  instance:
    instance-id: gateway
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/
