server:
  port: 7001

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka7001.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
